// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRCemoZU5dTP3Chsh1k_9SUZFSf58tpUo',
    appId: '1:710917594965:web:c83abb804842dcb55f99dc',
    messagingSenderId: '710917594965',
    projectId: 'firebase-projecet',
    authDomain: 'fir-projecet.firebaseapp.com',
    storageBucket: 'firebase-projecet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV_Bov7_sfbAw16WXaymupQvHDFMT8wkM',
    appId: '1:230074256519:web:',
    messagingSenderId: '230074256519',
    projectId: 'e-commerce-d8d97',
    storageBucket: 'firebase-projecet.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRCemoZU5dTP3Chsh1k_9SUZFSf58tpUo',
    appId: '1:710917594965:web:25d5a17a69fe92525f99dc',
    messagingSenderId: '710917594965',
    projectId: 'firebase-projecet',
    authDomain: 'fir-projecet.firebaseapp.com',
    storageBucket: 'firebase-projecet.firebasestorage.app',
  );
}
